[project]
name = "stem-games-m-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.0",
    "numpy>=2.0.0",
    "pandas>=2.2.0",
    "scikit-learn>=1.6.0",
    "sentence-transformers>=3.0.0",
    "torch>=2.12.0",
    "tqdm>=4.67.0",
    "transformers>=5.8.1",
]
